[package]
name = "simple_pretty"
version = "0.1.0"
edition = "2021"
description = "A confused library for outputting colored text to the terminal"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
